version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: readler-jellyfin
    restart: unless-stopped
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./medias:/medias
    environment:
      VIRTUAL_PORT: "8096"
      VIRTUAL_HOST: "jellyfin.readler.ovh"
      APP_UID: "1000"
      APP_GID: "1000"
      PUID: "1000"
      PGID: "1000"
      UID: "1000"
      GID: "1000"
      TZ: "Europe/Paris"
  jackett:
    container_name: readler-jackett
    image: linuxserver/jackett
    restart: unless-stopped
    volumes:
      - ./jackett/config:/config
      - ./jackett/blackhole:/downloads
    environment:
      VIRTUAL_PORT: "9117"
      VIRTUAL_HOST: "jackett.readler.ovh"
      APP_UID: "1000"
      APP_GID: "1000"
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Paris"
  syncthing:
    container_name: readler-syncthing
    image: linuxserver/syncthing
    restart: unless-stopped
    volumes:
      - ./syncthing/config:/config
      - ./medias:/medias
      - ./jackett/blackhole:/watch
    environment:
      VIRTUAL_PORT: "8384"
      VIRTUAL_HOST: "sync.readler.ovh"
      APP_UID: "1000"
      APP_GID: "1000"
      PUID: "1000"
      PGID: "1000"
      UMASK_SET: "022"
      TZ: "Europe/Paris"
  # client:
  #   container_name: abbi-play-client
  #   build:
  #     context: .
  #     dockerfile: "./client/Dockerfile"
  #   ports:
  #     - 100:4200
  #   volumes:
  #     - ./client:/usr/src/app
  #     - ./client/node_modules:/usr/src/app/node_modules
  #   environment:
  #     VIRTUAL_HOST: "play.abbi-studio.local"
  #     APP_UID: "1000"
  #     APP_GID: "1000"
  # api:
networks:
  default:
    external:
      name: nginx-reverse-proxy