version: '3.5'
services:
  emby-server:
    container_name: readler-emby
    image: emby/embyserver
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: "8096"
      VIRTUAL_HOST: "emby.readler.ovh"
      AUTO_UPDATES_ON: "true"
      APP_UID: "1000"
      APP_GID: "1000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./emby/config:/config
      - ./emby/medias:/home/medias
  jackett:
    container_name: readler-jackett
    image: linuxserver/jackett
    restart: unless-stopped
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    environment:
      VIRTUAL_PORT: "9117"
      VIRTUAL_HOST: "jackett.readler.ovh"
      APP_UID: "1000"
      APP_GID: "1000"
      TZ: "Europe/London"
  syncthing:
    container_name: readler-syncthing
    image: syncthing/syncthing
    restart: unless-stopped
    volumes:
      - ./emby/medias:/var/syncthing
    environment:
      VIRTUAL_PORT: "8384"
      VIRTUAL_HOST: "sync.readler.ovh"
      APP_UID: "1000"
      APP_GID: "1000"
  # client:
  #   container_name: abbi-play-client
  #   build:
  #     context: .
  #     dockerfile: "./client/Dockerfile"
  #   ports:
  #     - 100:4200
  #   volumes:
  #     - ./client:/usr/src/app
  #     - ./client/node_modules:/usr/src/app/node_modules
  #   environment:
  #     VIRTUAL_HOST: "play.abbi-studio.local"
  #     APP_UID: "1000"
  #     APP_GID: "1000"
  # api:
networks:
  default:
    external:
      name: nginx-reverse-proxy