version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: readler-jellyfin
    restart: unless-stopped
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./medias:/medias
    environment:
      VIRTUAL_PORT: "8096"
      VIRTUAL_HOST: "${READLER_DOMAIN:-readler.localhost}"
      LETSENCRYPT_HOST: "${READLER_DOMAIN:-readler.localhost}"
      JELLYFIN_PublishedServerUrl: "${READLER_DOMAIN:-readler.localhost}"
      APP_UID: "1000"
      APP_GID: "1000"
      PUID: "1000"
      PGID: "1000"
      UID: "1000"
      GID: "1000"
      TZ: "Europe/Paris"
  jackett:
    container_name: readler-jackett
    image: linuxserver/jackett
    restart: unless-stopped
    volumes:
      - ./jackett/config:/config
      - ./jackett/blackhole:/downloads
    environment:
      VIRTUAL_PORT: "9117"
      VIRTUAL_HOST: "jackett.${READLER_DOMAIN:-readler.localhost}"
      APP_UID: "1000"
      APP_GID: "1000"
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Paris"
  qbitorrent:
    container_name: readler-qbt
    image: linuxserver/qbittorrent
    restart: unless-stopped
    volumes:
      - ./qbt/config:/config
      - ./medias:/downloads
      - ./jackett/blackhole:/watch
    environment:
      VIRTUAL_PORT: "8080"
      VIRTUAL_HOST: "qbt.${READLER_DOMAIN:-readler.localhost}"
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
      UMASK_SET: "022"
      WEBUI_PORT: "8080"
networks:
  default:
    external:
      name: nginx-reverse-proxy
